### ISSUE TITLE
Make "Command Not Found Errors" Return Command List

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#133]
Pretty self explanitory. If the user sends a command that doesn't exist, e.g. `$dice_role`, the bot sends with the error message a list of roles that do exist. Ties in with the changes for #127.

### Additional Idea:
If the user sends an agrument that doesn't exist, such as `$role new`, the bot could provide a list of acceptable arguments.

**Problem**:
Help message for arguments could be problematic. For some commands the user can provide input, such as `$role requested_role`. I think an additional argument would need to be added so the bot knows to not treat the user input as an incorrect argument. (e.g. `$role request requested_role`)

**Comment by Jay-Madden** [comment]
I really like this idea, this would go really nicely with @mp7786 delete message feature

**Comment by patriciabac** [comment]
For this issue is send_default_help() in help_cog.py the function that prints out all the commands?

**Comment by Jay-Madden** [comment]
this is handled in the global error handler in ClemBot.py
