### ISSUE TITLE
!prof command search feature

### ISSUE THREAD

**Issue by Jay-Madden** [ClemBotProject/ClemBot#224]
Alot of people have a hard time remembering their professors name so we should add a search feature to allow for studnets to search the name of their professor to find out how its represented in the json asset file

cc @Nathan-Binkley

**Comment by zepthro** [comment]
#263 Adds the professor name linting feature

**Comment by Exper1mental** [comment]
Close since added in #294?

**Comment by Jay-Madden** [comment]
that pr was superceded, it needs to be reimplemented with a !prof search command

**Comment by mp7786** [comment]
So for this command the bot would reply with a list of names that are similar and could be scrolled if necessary.

**Comment by jkriste** [comment]
This feature has since been implemented.
