### ISSUE TITLE
Bot prefix causes errors if set to `<`

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#248]
If the bot prefix is set to `<`, it interprets users being mentioned (when at the beginning of the message) as commands to be executed, which yields the obvious `Command Not Found` error.

**Comment by Jay-Madden** [comment]
As discussed in discord this isnt actually a bug with clembot but more just a result of how discord internally represents mentions, we should just disallow this prefix entirely to prevent it

**Comment by jkriste** [comment]
Completed via #871
