### ISSUE TITLE
allow for teacher and class search in grades cog

### ISSUE THREAD

**Issue by Jay-Madden** [ClemBotProject/ClemBot#251]
This would be a tremendous feature to add, there are many search algos we can implement

**Comment by zepthro** [comment]
Could you tell me a little bit more of what you want?
How do you envision a "search." Are we thinking a big list like the !help command?
Or something like a search bar for class type?

**Comment by jkriste** [comment]
This feature has since been implemented with `!prof` and `!grades`.
