### ISSUE TITLE
Add Fuzzy String Matching to Grades.cog

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#311]
The idea is to add fuzzy string matching to the `grades.cog`. Specifically, for professor lookup and giving a list of suggested professors if the user's query turns up no results. Could do something similar for class lookup.

For example, someone searches for `Marisa Orr`. The bot wouldn't find any results so instead it would give a list of _"Did you mean..."_ including `marisa kikendal orr` and `marisa kikendal orr`. The same could be done for class lookup.

**Comment by Jay-Madden** [comment]
This would be an ideal scenario, however speed is a concern

**Comment by Iapetus-11** [comment]
Resolved by #762
