### ISSUE TITLE
Allow ClemBot Messages to Go on Starboard

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#331]
Pretty self explanatory. It appears messages posted by ClemBot are not evaluated for stars to see if they should be added to starboard.

For example:
![image](https://user-images.githubusercontent.com/14143235/116489942-2839ba80-a864-11eb-9a09-412ee855feae.png)

Does not show up on the starboard. It ought to be able to do this.

**Comment by Jay-Madden** [comment]
This is currently by design but i would not be opposed to a discussion about removing this restriction
