### ISSUE TITLE
Tag Cog: View Owned Tags

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#345]
The title encapsulates the idea. We want to be able to see what tags we own. Moderators (if not everyone) should be able to see a list of what tags a specific user owns.

It could also be really nice for tag management to have a tag preview where you can page through your tags while seeing them, with a trashcan to easily delete unwanted tags.

**Comment by smathep** [comment]
What did you envision for the tag preview stuff? Not sure how it would work well without doing one page per tag

**Comment by Exper1mental** [comment]
That is exactly the idea. There should be a list that doesn't have previews, and then on the following pages you go through each tag individually

**Comment by smathep** [comment]
Ah gotcha, ill play around with that

**Comment by smathep** [comment]
So any idea how to get reaction monitoring to delete a tag working with the paginate reactions since they are used for the chunking and display of all the tags?

**Comment by smathep** [comment]
Finally getting to work on this issue now

**Comment by smathep** [comment]
Now since the pageinate service controls the trashcan and arrow emotes, im not sure the best way to add another service that will monitor for say the ❌ emote or other emote to delete a tag, but I feel that is complex and unnecessary but am open to that discussion.

**Comment by Jay-Madden** [comment]
It's also functionality that should primarily be on the site

**Comment by glitchedcoder** [comment]
I feel `!tag delete <name>` is good enough for what it's worth.

**Comment by smathep** [comment]
Yeah the delete command is easy enough to use

**Comment by smathep** [comment]
@Jay-Madden this should be closed too. Already merged
