### ISSUE TITLE
Support Custom Server-Based API Keys

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#404]
I was thinking about how many of ClemBot's API features have rate-limits and the effect that could have as the bot scales up in usage. This gave me an idea.

What if we gave server owners the ability to use their own set of API keys? e.g. if a server wanted to eliminate having to compete with other servers for invoking the `!weather` command, which is rate limited to once every second, they could specify their own API key for it.

**Comment by Jay-Madden** [comment]
we'd then be responsible for api keys from other people, presumably tied to their personal info and/or financial info. frankly thats an unacceptable level of data risk for us to undertake. discord info is  one thing, potentially very serious PII is an entirely different matter and its not something we have the bandwith to deal with correctly.
