### ISSUE TITLE
D.py fork discussion and the future of ClemBot

### ISSUE THREAD

**Issue by Jay-Madden** [ClemBotProject/ClemBot#411]
Discord.py, our primary discord wrapper dependency has been discontinued

Reason: https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1

This issue is to server as a discussion of the way we want to move forward

This leaves us in a bit of a bad spot. The latest library commit is relatively stable with all new discord features (threads, buttons, interactions etc) with the notable exception of slash commands.

We have as i can tell a few different ways forward.

1. Wait and see if anyone forks the library
2. Fork the library ourselves and keep that up to date with what we need (I have already forked the library https://github.com/Jay-Madden/discord.py)
3. Switch to a new python library, either in python or choose a new language

Any and all thoughts and opinions are welcome at this point. This is an important change

**Comment by kspalm** [comment]
How much work do you see implementing slash commands? And then rewriting the rest of ClemBot to utilize them? How difficult or complex do you think it would be?

**Comment by Jay-Madden** [comment]
So having read the api, its no small feat to implement. AND its also goign to be a decent amount of work to figure out how to tie the slash commands into the existing normal commands. I have some ideas but nothing concrete. And that's IF we decide implement them at all. they are certainly not my favorite things

**Comment by kspalm** [comment]
So there's a 4th option, then: do nothing and hope we do get approved for the intent? I'd be okay with that if everyone else is, but I thought you wanted to start moving things over to slash commands anyways since it seems Discord is headed that way already.

**Comment by Jay-Madden** [comment]
Sadly no thats not an option. The discord api is still improving and changing. And d.py wont be updated to reflect these changes. which means eventually the library will stop working as is at all. We need to be ahead of that

**Comment by ashwinvin** [comment]
If you are thinking about switching to a new library. I would recommend [hikari,](https://github.com/hikari-py/hikari) since it is a **lot** more extensible than discord.py and would be more suitable for a bot like this, it also supports slash commands and buttons.

**Comment by Jay-Madden** [comment]
Hikari is def on the table, however the amount of work it would require to switch is incredibly significant. It would need a near total rewrite.

**Comment by Jay-Madden** [comment]
Nextcord has emerged as a possible option: https://github.com/nextcord/nextcord
as has pycord: https://github.com/Pycord-Development/pycord

**Comment by smathep** [comment]
Any known pros and cons between the two yet?

**Comment by Emimendoza** [comment]
I vote for pycord as nextcord hasnt included slash commands and to me it looks like just maintaining d.py but pycord looks like it not only maintains the d.py its based of off but also is still in active developing with added features (slash commands)

**Comment by Jay-Madden** [comment]
seems to be ya, we also have my fork that i made but havent touched. always an option
