### ISSUE TITLE
New Cog: Dad Joke / Riddle Guessing Game

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#428]
The idea is to create a cog with a bunch of dad joke questions with specified answers. The user sees the question and tries to guess what the answer is, and then ClemBot tells them if they got it or not. This could be multiple choice through emojis or reading the user message since we still have message access AFAIK.

**Comment by jkriste** [comment]
As mentioned in #630, this feature would be better suited for [SockBot](https://github.com/Jay-Madden/SockBot). See issue for more details.
