### ISSUE TITLE
Fix Using the Info Command on Other Users

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#447]
Currently, there is an issue with the info command when attempting to view someone else's info.
![image](https://user-images.githubusercontent.com/14143235/142944877-8348b51e-0dda-49a2-af06-ce44c6fd461c.png)

We need a fix so we can snoop on other people's stats. 😉

**Comment by Jay-Madden** [comment]
Ill get on this, its an annoying bug

**Comment by Jay-Madden** [comment]
fixed in #454
