### ISSUE TITLE
Memes Cog: Add support for emojis in text

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#481]
Should be pretty self-explanatory. Add support in the crab command for including emojis in the text, including discord emojis

**Comment by Jay-Madden** [comment]
i dont think this is possible, at least not easily. its likely a limitation of pillow

**Comment by jkriste** [comment]
Seems like it would be possible with this dependency: https://pypi.org/project/pilmoji/

**Comment by jkriste** [comment]
`!crab` command has been moved to SockBot, closing this issue.
