### ISSUE TITLE
Slots Command: Leaderboard and Playing Ratings

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#516]
The idea is to have a leaderboard, either server or global (or maybe both?) with high scores and then to also have player ratings and rankings (e.g. average slots score, number of times slots played, global ranking based on average slots score, etc.).

You could even have ranking tiers (Bronze, Platinum, Diamond, etc.) if you really wanted to go all-in with the ranking. :)

**Comment by Jay-Madden** [comment]
I have several improvements in this vein in the works right now, leaderboard will be build specific

**Comment by jkriste** [comment]
`!slots leaderboard` has been implemented for a while now, closing this issue.
