### ISSUE TITLE
Translate Cog: Autotranslate KeyError for Foreign Characters

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#530]
There appears to be an issue with the translate cog where it throws an error when using auto-translate and there are certain special or foreign characters in the text to-be-translated.

Example:
![image](https://user-images.githubusercontent.com/14143235/147983504-e397e413-2b58-4275-9c66-62ded23fb234.png)

**Comment by Jay-Madden** [comment]
cc @smathep

**Comment by STEVE4git** [comment]
![Screenshot from 2022-06-23 18-14-28](https://user-images.githubusercontent.com/93275421/175424138-e9f7d238-bd1a-471b-9b6a-351e395e4b89.png)
@Jay-Madden Fixed this awhile ago issue needs to be closed

**Comment by jkriste** [comment]
Resolved in a previous PR.
