### ISSUE TITLE
Moderation Feature: View Own Infractions

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#540]
The title says it all. By default, it seems like users should be able to see their own infractions (or have them DM'd to themselves).

Currently, users can either see no infractions or all infractions.

Below is what is shown when a user without one of the necessary claims tries to view their own infractions:
![image](https://user-images.githubusercontent.com/14143235/148178291-4eb9fce8-6555-45e8-9c95-636fc397edea.png)

**Comment by Jay-Madden** [comment]
This is actually a really good idea i never thought of, wouldn't be too hard to add either

**Comment by Jay-Madden** [comment]
closed in #551
