### ISSUE TITLE
Add Ephemeral Messages with Helpful Tips and Suggestions

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#545]
Discord.py supports [ephemeral messages](https://support.discord.com/hc/en-us/articles/1500000580222-Ephemeral-Messages-FAQ) in response to interactions (such as clicking on a button). I suggest utilizing this through the bot to provide helpful tips and suggestions to the user.

For example, such a message could be used when someone is configuring claims for `@everyone` to suggest our default claims configuration:
```
claims_view
emote_add
manage_class_add
tag_add
```

Another example would be for my weather cog, where someone checks the weather while specifying the state `City, State` but not the country `City, State, Country`. Since this is not a valid input and could either throw an error or return the wrong locational weather, it would be good to have a message letting the user know their input may cause issues.

**Documentation:**
[Discord.py Docs - Interactions](https://discordpy.readthedocs.io/en/master/api.html?highlight=interaction#discord.InteractionResponse)
[Discord Dev Portal - Interactions](https://discord.com/developers/docs/interactions/receiving-and-responding)

**Comment by Jay-Madden** [comment]
sadly this is a slash command only feature
