### ISSUE TITLE
Latency Feature: Ping-Pong Command

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#548]
I propose implementing a ping-pong command to check latency and bot responsiveness. When the user invokes `!ping`, the bot would respond with `Pong!`. Then, the bot will edit the message to include the milliseconds between when the user's message was sent and when ClemBot's response was sent.

**Comment by Jay-Madden** [comment]
I thought we already had an issue for this but i guess not, this is a great idea and its a command ive been leaving available for someone new or just starting out to work on. Would def accept a pr for this

**Comment by jdkenne** [comment]
Hi, is the file where the commands are defined in located in the cogs folder? I would like to help figure this out pretty quickly.

**Comment by Jay-Madden** [comment]
The cogs folder contains the commands yes, this will need to be a new cog/file. You can find more information on clembots architecture in the readme
