### ISSUE TITLE
Bug: Chain Cog Doesn't Recognize Commands with Different Letter Case

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#585]
The chain cog doesn't recognize commands with a different letter case than what is specified in the bot. This issue is specific to the chain cog.

Here is an example:
![image](https://user-images.githubusercontent.com/14143235/152186262-26795169-8549-4edf-8ad4-552bc664c035.png)

**Comment by Exper1mental** [comment]
@Emimendoza

**Comment by Emimendoza** [comment]
This issue is not specific to chain command. The code the chain command uses to look up commands was copy-pasted from the help command.
![image](https://user-images.githubusercontent.com/24688719/152196545-80882173-9dd8-4ea5-ba5c-01085eb524bb.png)

**Comment by Exper1mental** [comment]
Good point, I'll add a separate issue for that.

**Comment by Jay-Madden** [comment]
This along with #587 are not things that will be worked on
