### ISSUE TITLE
Bug: Chain Cog Falsely Detected Bot Command Prefix in Text Input

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#586]
The chain cog fails to distinguish between instances when the bot command prefix is being invoked and cases when it is a mid-text character as part of the input (e.g. `hi!` and `hi! hello` throw an error)

Example:
![image](https://user-images.githubusercontent.com/14143235/152186603-5290f662-20e4-4239-836e-e9bf789103cc.png)

Using quotation marks doesn't appear to help either:
![image](https://user-images.githubusercontent.com/14143235/152186815-27cf5a24-e8e4-4edc-9d88-478ac15bd92e.png)

**Comment by Exper1mental** [comment]
@Emimendoza

**Comment by Emimendoza** [comment]
I thought about this when implementing the chain cog. You just have to escape the prefix like if it was discord text formating

for example:
![image](https://user-images.githubusercontent.com/24688719/152195384-f74eb684-b5c6-4fb5-a8c9-768114f9292e.png)
![image](https://user-images.githubusercontent.com/24688719/152195422-f3903257-a26a-4175-9e80-50281c18a618.png)

**Comment by Emimendoza** [comment]
@Exper1mental
