### ISSUE TITLE
Bug: Help Command Doesn't Recognize Input Commands with Different Letter Case

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#587]
#585 the chain cog shares this issue since the code was copy-pasted from the help command code.

![image](https://user-images.githubusercontent.com/14143235/152197307-088c9a86-1232-4460-9d4b-4dc906d1d503.png)

**Comment by Jay-Madden** [comment]
This is an easy fix overall, it does need to possibly take into account the ignore_case option on the command but thats not the most pressing issue

**Comment by Jay-Madden** [comment]
would def accept a pr for this

**Comment by jdkenne** [comment]
Would it be better to just implement that or just force everything into lowercase for it to be read?
