### ISSUE TITLE
Emote_Cog.py: Unicode Emoji Aren't Supported

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#605]
This is a bit of an edge-case bug, perhaps even a #won't-fix, but I thought it was still worth noting.

The emote cog doesn't work with Unicode emojis. This isn't really shocking but I suppose some servers might like having shortcuts or appreciated versions of Unicode emojis they frequently use.

**Example:**
![image](https://user-images.githubusercontent.com/14143235/154355547-a8fca137-bab7-4fb7-be31-71595f084f8b.png)

**Comment by Jay-Madden** [comment]
This is due to how discord handles those unicodes, they arent files stored on the CDN, we cant really do anything about this.
