### ISSUE TITLE
Discussion: What should the prefix be

### ISSUE THREAD

**Issue by Jay-Madden** [ClemBotProject/ClemBot#61]
Currently we are using `$` due to a conflict with `!` but any other ideas are welcome

**Comment by Exper1mental** [comment]
I think the prefix should be `$ ` (with a space on the end) so that it is more clear the $ is what is used to call the bot. Not really an issue now but it could cause confusion if command abbreviations were added.

**Comment by Jay-Madden** [comment]
Closed since forever ago with dynamic prefixes
