### ISSUE TITLE
Bug: Professor List Page Number Text Repeats Based on Number of Times Command is Invoked

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#631]
The `!prof list` command's "page # of ###" embedded element has a duplicating issue. Every time the command is called, an additional  "page # of ###" shows up (except only the one at the bottom updates when you change pages) 

The first time the command is called:
![image](https://user-images.githubusercontent.com/14143235/159126045-85c24510-6683-4007-827d-b9edaf67fb93.png)

The second time:
![image](https://user-images.githubusercontent.com/14143235/159126050-01437f13-66f6-45d8-a06e-4f5b0750c4f1.png)

The third time:
![image](https://user-images.githubusercontent.com/14143235/159126061-4bda8e15-7de7-4ee4-8f78-5a27b68f9b5b.png)

AFAIK this issue only affects this specific command.

**Comment by Jay-Madden** [comment]
Closed in #632
