### ISSUE TITLE
Bug: Starboard Splitting Emoji in Long Message

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#635]
In long messages, starboard will just split the message (I'm assuming at 1024 characters?) regardless of what is there.

**For example:**
![image](https://user-images.githubusercontent.com/14143235/159749808-5e1b5478-4d8e-4456-9a86-7eeb7684a414.png)

Instead, starboard should split the message at the most recent space in the text (or something like that), and only split at the 1024th character if no such space can be found (such as for a really long URL).

**Comment by Jay-Madden** [comment]
This is a good idea, however it is more complicated then it looks. This has partly already been done in the source_code_cog.py file if anyone wants to look there. I would accept a PR, starboard needs some TLC

**Comment by smathep** [comment]
@Jay-Madden what was the reasoning for splitting the message like that if it isnt paginated?

**Comment by Jay-Madden** [comment]
Splitting on 1024?

**Comment by smathep** [comment]
Yes

**Comment by jkriste** [comment]
> Yes

It's the field limit for discord's embeds.

**Comment by smathep** [comment]
Ohhh. That makes more sense
