### ISSUE TITLE
Bug: Quoting Message Fails if Character Count Exceeds 1024

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#636]
The quoting message feature appears to not work and throws an error in `#clem-bot-error-log` if a message has more than 1024 characters. This includes characters used for emoji.

Quotations ought to be broken up like starboard does (and perhaps even paginated) if the character count is exceeded.

**For example:**
![image](https://user-images.githubusercontent.com/14143235/159752290-e5d6bfa1-27c2-42ed-956d-bc93ad2773bf.png)

**Yields in `#clem-bot-error-log`:**
![image](https://user-images.githubusercontent.com/14143235/159752347-36f2ce99-1442-4fe2-842f-e16f433eab90.png)

**Comment by Jay-Madden** [comment]
Great catch on this one, we should probably just truncate and let people click the link to the message

**Comment by Jay-Madden** [comment]
Would be an easy pr
