### ISSUE TITLE
Bug: Trashcan Emoji Does Not Timeout for Several Commands

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#638]
I noticed the other day that several of ClemBot's commands appear to have no trashcan emoji timeout, meaning that anytime in the future the command query author can click the trashcan for ClemBot to delete the message. Specifically, I noticed that an `!info` command message I had sent half a day before still had the trashcan, and when pressed still deleted the message.

If I understand correctly, this also means that ClemBot is basically creating and storing an ever-growing list of messages in the `self.messages` array of `delete_message_service.py` until the bot crashes or restarts.

### Commands confirmed to have the issue
- `info`

### Commands suspected to have the issue
- `source list` (`source <file-name>` works just fine)
- `tags`
- `help`
- `define` (but not `define` error messages)
- `grades` (specifically `grades <course-ID>` haven't checked others)
- `convert` / `bconvert` error messages
- `prof list`
- `roles`
- ClemBot error messages (e.g. command not found)

### Commands that do not have the issue 
- `slots`
- `ogslots`
- `translate`
- `define` error messages
- `convert` / `bconvert`
- `source print`

Anything not listed hasn't been checked by me.

By suspected, I mean that I haven't tried pressing the trashcan on the output from one of these commands to confirm ClemBot will still delete the message.

### Example
![image](https://user-images.githubusercontent.com/14143235/160284112-9fb31c58-67f8-4bb7-a360-79f7694a65ae.png)

**Comment by Jay-Madden** [comment]
The info command doesn't have a set timeout, it will last for as long as the bot hasn't restarted, adding a timeout is trivial if we want to do that

**Comment by arock475** [comment]
Could I be added to this issue? And clarifying question, would you prefer adding a default timeout value or adding a timeout value to each of the services which do not have it?
