### ISSUE TITLE
Ping Cog: Ping a specific website

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#644]
The idea here is to expand the ping command into being able to ping specific websites. This serves as a sanity check to see if the website is up (and the URL is valid) as well as to see if it is running sluggishly (or if the person's internet might be the culprit for connection issues).

I'm guessing URLs would probably first need to be scanned through a URL checker API looking for malicious websites, although I'm not sure how dangerous that would actually be when using a command like this.

**Comment by butteredwaffles** [comment]
@jkriste attempted this one too

**Comment by smathep** [comment]
Closed by #644
