### ISSUE TITLE
Info Cog: Server-specific starboard count

### ISSUE THREAD

**Issue by jkriste** [ClemBotProject/ClemBot#645]
Starboard already needs some love, but @smathep came up w/ a good idea for the info cog: display how many times a person made it to the starboard. Might not be possible to count how many times a person made it to the starboard before the feature would supposedly be implemented, but if possible - it should be accounted for.

I'd be more than willing to work on starboard + either the info or starboard cog, depending on which is chosen.

**Comment by Exper1mental** [comment]
I like the idea, but I think it should be tied to a new cog, a starboard cog, that provides the info. 

Command input could be something like:
`!starboard @username`

Invoking just `!starboard` could then display a leaderboard, similar to the slots leaderboard

**Comment by jkriste** [comment]
Also include server-specific starboard threshold.
