### ISSUE TITLE
Moderation Feature: Allow Lower Rank Roles to Moderate Higher Rank Roles

### ISSUE THREAD

**Issue by Exper1mental** [ClemBotProject/ClemBot#658]
On some servers, it is desirable to give select members, e.g., Server Boosters, high and prominent roles within the server. For example, Clemson Esports does this for Server Boosters. However, this creates a problem for moderators. If the moderator role is of a lower rank than the server boost role, moderators are unable to moderate server boosters via ClemBot!

ClemBot should allow lower rank roles to moderate higher rank roles, with the obvious exception of administrators. If there is concern about unintended consequences for some servers, a new claim to apply to roles as needed to give them this override.

**Comment by jkriste** [comment]
This seems more like a role hierarchy issue, if I'm honest.

**Comment by Jay-Madden** [comment]
The solution to this is a hidden "staff" role that all mods have that is higher then everyone else but not shown on the side
