### ISSUE TITLE
Claims Broken

### ISSUE THREAD

**Issue by Emimendoza** [ClemBotProject/ClemBot#757]
![image](https://user-images.githubusercontent.com/24688719/184250532-1410ab38-be01-478b-bf21-fe2fa81a3aac.png)
User had the tag add claim on the image below
![image](https://user-images.githubusercontent.com/24688719/184250596-361fc50c-9a8f-474a-9715-abe3cd86df51.png)

**Comment by Jay-Madden** [comment]
closed in #758
