### ISSUE TITLE
Feature: Disabling Commands Server-wide

### ISSUE THREAD

**Issue by jkriste** [ClemBotProject/ClemBot#765]
Have the ability to enable and disable certain commands server-wide.

Current thoughts:
- Command Name: `command` (aliases: `cmd`)
- Arguments: `<command name> [enable | on | disable | off]` (if given the command name it will let the user know if it's enabled or disabled (does not require claim))
- When enabling or disabling commands (i.e., not `!cmd <command name>`) the `manage_commands` claim is required.
- Only applies to a command or a group of commands. You cannot disable a sub-command, i.e., `!tag add`.
- Possible idea: have another claim to bypass disabled commands? Probably named `bypass_disabled_commands`?
- Command Service
  - Might have to rename from `CommandMetricsService` just to `CommandService` if we don't want to add another service.
  - On each command run, the bot will request from the API whether or not that command is disabled. If so, the user will be notified that it's been disabled server-wide.
- Additions to Commands Route
  - **[GET]** `bot/commands/{GuildId}/{CommandName}` - Will check against a `List<string>` from the API and will return a boolean, `true` if enabled, `false` if disabled.

**Comment by Jay-Madden** [comment]
First of all, excellent work. some thoughts

```
1. we still need data model design
2. we should consider adding an option to either fail silently or report that the cmmand is disabled
3. This will require additions to the docs site
4. we will need a put end and delete endpoint to add and delete mappings
```
overall youve covered most of the bases
