### ISSUE TITLE
Same channel name checking for the !class command

### ISSUE THREAD

**Issue by kspalm** [ClemBotProject/ClemBot#769]
Currently, it is possible to create a class channel with the same name as one already made. Mods have to delete the new channel and it's just overall not ideal.

Proposed solution:
Add in a check during the class creation process that checks if there's another channel with the same course number and instructor name. If there is one, then direct the user to that channel with a link. Otherwise the process can continue as normal.

**Comment by jkriste** [comment]
`!class` command has been moved to SockBot, so this feature will not be implemented here.
