### ISSUE TITLE
Bug: RemindMe creates duplicate events

### ISSUE THREAD

**Issue by tallendev** [ClemBotProject/ClemBot#773]
Bug: !remindme sends two requests; creates two duplicate events. Replicated with minutes and days. 

Describe the solution you'd like: it should create one event : It should create one event : )

![remindme2](https://user-images.githubusercontent.com/5674283/186262499-6410caf2-47ae-4426-a8eb-c78f910cd5b1.PNG)
![remindme](https://user-images.githubusercontent.com/5674283/186262500-a15ced08-d6f0-451f-9493-a35c15ef7d87.PNG)
<img width="625" alt="tworequests" src="https://user-images.githubusercontent.com/5674283/186262554-9d8200c7-ba6b-49f8-9ed3-5a9fcae52ceb.png">

**Comment by Jay-Madden** [comment]
This one is happening on every reminder and its quite bizzare

**Comment by jkriste** [comment]
So the current idea is that somehow there was 2 instances of the bot (or something in the bot), which caused the issue.

Truly a bizarre issue, but not directly related to the remind cog.
