### ISSUE TITLE
Emote Add Not Working

### ISSUE THREAD

**Issue by MadduxRhodes** [ClemBotProject/ClemBot#777]
There is an old url and a new url for the emotes. So the add emote command produces an error message of "list index out of range."
![emoteproblem](https://user-images.githubusercontent.com/49253807/186972955-25b23ec9-dab4-4f23-be8e-8adc40097bfa.png)

**Comment by MadduxRhodes** [comment]
don left the same message

**Comment by Jay-Madden** [comment]
Duplicated in #776
