### ISSUE TITLE
Starboard Rewrite

### ISSUE THREAD

**Issue by MatthewPerryDev** [ClemBotProject/ClemBot#821]
I've created this issue as a means of discussing and organizing features that will be implemented in a starboard rewrite.

**Comment by MatthewPerryDev** [comment]
Some proposed changes:

- [ ] The addition of a leaderboard
- [ ] Persistence of previously starred posts
- [ ] A command to check a users total # of stars
- [ ] The ability to customize the starboard threshold on a per server basis

**Comment by Jay-Madden** [comment]
Persistence is the big thing we need to start with, everything else can come after
