### ISSUE TITLE
Enhancement: Force-ban if member not found.

### ISSUE THREAD

**Issue by jkriste** [ClemBotProject/ClemBot#855]
**Is your feature request related to a problem? Please describe.**
Right now, ClemBot will error out saying the user was not found if they left the server before the `!ban` command could be executed.

**Describe the solution you'd like**
ClemBot should force-ban them through `discord.Object` objects, as suggested in [this issue](https://github.com/Rapptz/discord.py/issues/1223#issuecomment-381804122).

Bonus points if deleting prior messages still works.

**Comment by butteredwaffles** [comment]
Hey @jkriste, would you still like to handle this or is it okay if I give it a shot as a first-time contribution?

**Comment by jkriste** [comment]
@butteredwaffles Go ahead, I'll assign the issue to you. Thanks!

**Comment by smathep** [comment]
Closed by #855
