### ISSUE TITLE
Bug: Command cog fails to parse sub-commands

### ISSUE THREAD

**Issue by jkriste** [ClemBotProject/ClemBot#864]
![image](https://github.com/ClemBotProject/ClemBot/assets/16947464/62bd5db9-4f78-4af4-a191-b35f6abd3c8a)
ClemBot currently is having issues parsing sub-commands when running the `command` cog.

A good starting point would be checking out the [CommandConverter](https://github.com/ClemBotProject/ClemBot/blob/master/ClemBot.Bot/bot/utils/converters.py#L25) which parses the plain-text into a command object.

**Comment by smathep** [comment]
Closed by #864
