### ISSUE TITLE
Feature: Choose command

### ISSUE THREAD

**Issue by jkriste** [ClemBotProject/ClemBot#866]
### About
This feature would add a new command, called `choose`. Given a comma-separated list of items, ClemBot will pick one of the items at random.

### Outline
**Command Syntax:** `!choose <items...>`
**Preconditions (Optional):** Size of items is >1.
**Expected Output:** One of the items will be chosen at random. ClemBot will let the user know of its choice.

### Examples
| Command | Output | Explanation |
|-------------|---------|--------------|
| `!choose a, b, c, d, e` | `a`, `b`, `c`, `d`, or `e`, equal chance. | Comma-separated list with spaces. |
| `!choose a,b,c,d,e` | `a`, `b`, `c`, `d`, or `e`, equal chance. | Comma-separated list with no spaces. |
| `!choose a` | Error. Optionally `a`, if and only if the item given does not contain whitespace. | The list of items is of size 1. |
| `!choose` | Error. | No options were supplied. |
| `!choose a b c d e` | Error. | Items were not separated with commas. |

### Miscellaneous
- Item weights wouldn't be too bad of an idea, but further complicates the syntax of the items. Definitely optional.

**Comment by ShivamPatel-24** [comment]
Hi @jkriste I would like to take on this feature. Please consider assigning it to me.

**Comment by smathep** [comment]
> Hi @jkriste I would like to take on this feature. Please consider assigning it to me.

Assigned to you

**Comment by smathep** [comment]
@ShivamPatel-24 Apologies, this issue was being worked on by someone already, just the assignee wasn't updated

**Comment by arock475** [comment]
Hello I was working on this before. My bad for not commenting sooner

**Comment by smathep** [comment]
Assignee updated

**Comment by jkriste** [comment]
Completed via #868
